VERTEX_PROJECT = "chatbot-rrhh-dd8c9"
VERTEX_LOCATION = "us-central1"
VERTEX_MODEL = "gemma-1.1-2b"
VERTEX_CREDENTIALS_JSON = """
{
  "type": "service_account",
  "project_id": "chatbot-rrhh-dd8c9",
  "private_key_id": "f8cdcbf68a5533a1e5143451eac4689c34e5daa2",
  "private_key": "-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDV9jEDKal0LtvD
c8ZeooXcQgOkckwk0fCIihiuA+/adWEphh+kZ1Wmuiu/Vo6CT0tq3g/ZpKAsfHwZ
vEN9QtzJNRcr9Nve0AncK3fYuh9uusnE2jiqzuWPm4H2IG6lAL50xr77cPozdERU
83s0DcB7kC2Zi9hyxarbkJw91jNhZm7niJkbhGkF/Kv7g6acgK4gIDB/T2MhfzmQ
n1lRouMFT40qG3PPd8JYui1ajXfAeBEAFv1AbbePeUqRuCudSq64DwzvvqnYrrQp
1m4GILOgvUPZZ/ju+ffSxji95Gy/L6AlIgFjIUtGjY+t+Jsmfl85BvWc4WZaBJln
hJMuTz3NAgMBAAECggEASn8iOJIwdIn+LZLpfjjDN9nqT78WIPnR8JB4oFoxkJQv
BNi0urbZ/Se0JLY7/0Yhoa94wFRQCr07LnC85Oe7XPk1vLHQPkecL0MZQuYnHJQ/
vWEnut0306UW/n3zWFMmfR1YEM8Y5oJ0akmuW4TwQHWGUwB8mBWX9EPpCqTClgYD
inEdwwMIV9hY5Xr9Z522Ymf+kw8iNXPPVz7eyU6MhBHCdEL0qgz04Tb3WrSws8C6
9mvd1ONcSW5zm8QI7pPns6LQBh9Iwhkrh3eefQa1Fn/3ydxGFM7FZzBN/jGWkym0
B3K68bZPvSiJL2GmT++G+fozFkkqO/t+aQPjHL1eJwKBgQD5LY2HmsqO3EyGk7ok
quraoh5nLcWqNm+sAlQRiwurZItoJkKX/PDLQZXPjo55urJFt9uZGq3BgrqcOQPA
5znVbWxpK5Lh8Lzm0j3tdsxCb9QkLljIf8Tr6cwP20yovB8k67HcoLUa0eOVTK5u
ZN0ctpKIXVJ2VH+TCZBqExwkgwKBgQDb0dBMpGYkvJe7Hm12flkruPJ6dEUCPpGl
EfaN65wJr1vlzqAV/42c+7xgg/m0HNV/ioyaOzLHmZinZkcxPxLcBdzl5ED5j//2
8jgup3iLI2FDrtnD34cOB+lBnJumaGy0Z97WNHR2vL4lWYABwjtgMHbwZ12z8qzA
n8tmj/SjbwKBgD3qyNliaGT5bvad7MpBwlwTntRqtkxmfHdUmMlHMN4k/NMjdrbH
vpnzMSPDO7oZ30SdvC6eR4DnWDGLpVgg3Okg6Kh1kGkeZgJBSewg8f6sRR28eolP
3oH0taVXDAR9wottGeRF9tq0PwYRaOK7o4oH//9smRoYQx8paD5Dg2G7AoGAU9OP
O6r1yMyikBjqZWWJW8MLtObh6hkyMWDIRRa0Sn007k39fmYV+ueEzsmFT8ovIJQV
SjuJAdTxAeVfAMisyHrz4jdJD+J6GhIEmsYCkgzL6qOjJ672McOSkBLIyIzJ54I0
2Drort8LI/MdfY40VlolAUhp01WXy10kk9gR0sECgYAJ7YuPiCvI4/IUzlVrslKE
hho3QVWKgMzzSCc2xZcE447aJOWLwrAJgiah8EaRMShESfMZsuJXtzFcVdWny4yB
5yMYJcNg1LKA+BPBp6UnDx5nZxiUxZeBK2pfJcSHiJV0c5qOjZLJJ5wfbxBxnYYB
UpFS2nt/fv6LD45E5k67+g==
-----END PRIVATE KEY-----
",
  "client_email": "service-chatbot@chatbot-rrhh-dd8c9.iam.gserviceaccount.com",
  "client_id": "117511836921756850727",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/service-chatbot%40chatbot-rrhh-dd8c9.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
"""
